### ISSUE TITLE
Stop bump issues

### ISSUE THREAD

**Issue by fulldecent** [Genobank/biosample-permission-token#7]
@duribebe please grant @xpepermint and I access to all repositories so we can change some settings

**Comment by fulldecent** [comment]
@duribebe ^^

**Comment by xpepermint** [comment]
@fulldecent @duribebe explain, status?

**Comment by fulldecent** [comment]
We are waiting here for Daniel to provide admin access on these repositories. Then I can turn off all these unrelated Nokogiri version bump messages

**Comment by xpepermint** [comment]
@duribebe ping.

**Comment by fulldecent** [comment]
fixed
