### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by MoMannn** [Genobank/biosample-permission-token#9]
Choose a license for the smart contract. If you want to verify a contract on etherscan you need to choose a contract.

<img width="732" alt="Screenshot 2020-11-13 at 15 50 39" src="https://user-images.githubusercontent.com/8865298/99085402-6bf77b00-25c8-11eb-8f71-19e3de7f492f.png">

**Comment by fulldecent** [comment]
Please choose NO LICENSE.

Also, our smart contracts should have a copyright notice at the top of each file: 

Copyright GenoBank.io. All rights reserved.

---

I will contact etherscan to add a better option to that dropdown.
